import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('heading', { name: 'Faculty Management System' }).click();
  await page.getByRole('button', { name: 'Admin/Faculty' }).click();
  await page.getByRole('heading', { name: 'Login to your account' }).click();
  await page.getByPlaceholder('Enter Your Email').click();
  await page.getByPlaceholder('Enter Your Email').click();
  await page.getByPlaceholder('Enter Your Email').fill('naranaveen576@gmail.com');
  await page.getByPlaceholder('Enter Your Password').click();
  await page.getByPlaceholder('Enter Your Password').click();
  await page.getByPlaceholder('Enter Your Password').fill('admin12345');
  await page.getByRole('combobox').selectOption('User');
  await page.getByRole('button', { name: 'LOGIN' }).click();
  await page.getByRole('link', { name: 'Add Workshops' }).click();
  await page.getByRole('button', { name: 'Add Workshop' }).click();
  await page.locator('div').filter({ hasText: /^Faculty Mail:$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Faculty Mail:$/ }).getByRole('textbox').fill('test@gmail.com');
  await page.locator('div').filter({ hasText: /^Name of Workshop:$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Name of Workshop:$/ }).getByRole('textbox').fill('Annual');
  await page.locator('div').filter({ hasText: /^Venue:$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Venue:$/ }).getByRole('textbox').fill('Bangalore');
  await page.locator('div').filter({ hasText: /^Started On:$/ }).getByRole('textbox').fill('2024-09-11');
  await page.locator('div').filter({ hasText: /^Ended On:$/ }).getByRole('textbox').fill('2024-09-20');
  await page.locator('div').filter({ hasText: /^No\. of Days:$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^No\. of Days:$/ }).getByRole('textbox').fill('20');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Publish Journals' }).click();
  await page.getByRole('button', { name: 'Publish' }).click();
  await page.locator('div').filter({ hasText: /^Publisher Name:$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Publisher Name:$/ }).getByRole('textbox').fill('Naveen');
  await page.locator('div').filter({ hasText: /^Department:$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Department:$/ }).getByRole('textbox').fill('CSE');
  await page.locator('div').filter({ hasText: /^Title of Paper:$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Title of Paper:$/ }).getByRole('textbox').fill('Advance Learning');
  await page.locator('div').filter({ hasText: /^Volume:$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Volume:$/ }).getByRole('textbox').fill('24');
  await page.locator('div').filter({ hasText: /^Issue:$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Issue:$/ }).getByRole('textbox').fill('New Tech');
  await page.locator('input[type="date"]').fill('2024-09-03');
  await page.locator('textarea').click();
  await page.locator('textarea').fill('sd');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Apply Leave' }).click();
  await page.locator('div').filter({ hasText: /^1Leave$/ }).getByRole('button').click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('headache');
  await page.getByRole('button', { name: 'Send' }).click();
  await page.getByRole('link', { name: 'Profile' }).click();
  await page.getByText('FacultyTrack').click();
  await page.getByText('FacultyTrack').click();
  await page.getByRole('link', { name: 'LogOut' }).click();
  await page.getByPlaceholder('Enter Your Email').click();
  await page.getByPlaceholder('Enter Your Email').fill('admin@gmail.com');
  await page.getByPlaceholder('Enter Your Password').click();
  await page.getByPlaceholder('Enter Your Password').fill('admin12345');
  await page.getByRole('combobox').selectOption('Admin');
  await page.getByRole('button', { name: 'LOGIN' }).click();
  await page.getByRole('link', { name: 'Faculties' }).click();
  await page.getByRole('link', { name: 'Approve Workshops' }).click();
  await page.getByRole('link', { name: 'Approve Journals' }).click();
  await page.getByRole('link', { name: 'Approve Leave' }).click();
  await page.getByRole('link', { name: 'LogOut' }).click();
});